### ISSUE TITLE
More stars in the ages VAC than in the main catalog?

### ISSUE THREAD

**Issue by jobovy** [svenbuder/GALAH_DR3#1]
Hi @svenbuder!

I was downloading the latest GALAH DR and noticed that there seem to be many more entries in the ages VAC than in the main catalog file. That is, there are 651752 entries in the ages VAC while there are only 588571 in the main catalog. All of the entries in the ages VAC seem to have a unique `sobject_id`. Are these duplicates? Your code for joining the two catalogs works fine, but I just wanted to check whether this difference in the numbers is expected?

On another topic, when will the spectra be released? We are eagerly looking forward to those 🙂

Thanks!

**Comment by svenbuder** [comment]
Hi @jobovy,

There is a difference because we have a main catalog for all spectra (*allspec*) and a smaller clean version with only one entry per star (*allstar*).

The ages VAC has entries for all spectra individually with low flag_sp, that is, a large portion of the *allspec* file. *allspec* contains all measurements for all spectra, whereas *allstar* only contains 1 measurement per star (from the highest S/N spectrum). So the additional entries are from repeats of the same star.

We are still having issues with ingesting the spectra - I will make sure that you will know once they are online 🙂 I assume you want to download all spectra anyway? In that case maybe shoot an email to galah.helpdesk@gmail.com, because I think it might be easier to provide you with an HDF5 file.

Best,


Sven

**Comment by jobovy** [comment]
Hi @svenbuder, thanks for the clarification! I've now added an interface to GALAH DR3 to my [`gaia_tools`](https://github.com/jobovy/gaia_tools) package that also optionally loads the VACs.

Yes, we would just want to download all of the spectra 🙂, so good to know that they are available already; I'll email the helpdesk!

Thanks!
